Repository Meloong-Git/PCL, pull requests merged in 2024-10, with the labels that each got.

#4868 MyImage 控件
  Plain Craft Launcher 2/Controls/MyImage.vb
  Plain Craft Launcher 2/Modules/Base/MyBitmap.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: 等待提交者, · 新功能

#4810 新功能：原版服务端下载功能
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
Labels: 处理中, · 新功能, 🟨 中

#5001 利用 action bot 进行 issue 查重
  .github/workflows/issue_similarity.yml
Labels: · 新功能, 社区处理中

#5025 修正了一处bug
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml.vb
Labels: · Bug, 等待确认
