Repository Meloong-Git/PCL, pull requests merged in 2024-12, with the labels that each got.

#5098 Fix #5096
  Plain Craft Launcher 2/Modules/ModMusic.vb
Labels: 处理中, · Bug, 🟨 中

#5212 Change the download page version filter item
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadMod.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadPack.xaml
Labels: 处理中, · 优化, 🟨 中

#5229 自动编译时添加 Help.zip
  .github/workflows/build.yml
Labels: 等待提交者, · 优化
