Repository Meloong-Git/PCL, pull requests merged in 2024-08, with the labels that each got.

#4441 Add 1.21.1 to Mod and Modpack downloadpage version filter
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadMod.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadPack.xaml
Labels: 处理中, · 优化, 🟥 高

#4449 fix: 检测愚人节版本所用时区不正确
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadClient.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
Labels: 处理中, · Bug, 🟨 中

#4291 添加国内 Mod 镜像下载源
  Plain Craft Launcher 2/Modules/Base/ModNet.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModMod.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml.vb
Labels: 完成, · 新功能

#4415 Close 添加对 MCC 15周年披风的翻译 #4366
  Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
Labels: 处理中, · 优化, 🟨 中

#4438 Revise the translation of Kitchen Sink
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadPack.xaml
Labels: 处理中, · Bug, 🟩 低

#4491 fix: 下载 NeoForge 时，从未使用镜像源
  Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
Labels: · Bug, 等待确认

#4485 Fix 导出崩溃报告中的 “游戏崩溃前的输出.txt” 可能乱码 #4482
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
Labels: · Bug, 等待确认

#4541 优化：当有 Mod 选中时在下方空开一定空间方便操作
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionMod.xaml.vb
Labels: 处理中, · 优化, 🟨 中

#4404 新功能：简单的本地 Mod 筛选
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionMod.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionMod.xaml.vb
Labels: 处理中, · 新功能, 🟨 中

#4621 修改 NeoForge 介绍
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadNeoForge.xaml
Labels: 处理中, · 优化, 🟨 中

#4498 LittleSkin 登陆失败时使用 Json 返回的错误数据中的建议
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
Labels: 处理中, · 优化, 🟨 中
