Repository Meloong-Git/PCL, pull requests merged in 2024-09, with the labels that each got.

#4709 修复因未使用模组列表搜索并尝试移除搜索结果导致的异常#4691
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionMod.xaml.vb
Labels: 处理中, · Bug, 🟪 极高

#4743 新功能：支持加载 WebP 格式图片的资源图标
  Plain Craft Launcher 2/Application.xaml.vb
  Plain Craft Launcher 2/Modules/Minecraft/MyCompItem.xaml.vb
  Plain Craft Launcher 2/Modules/Minecraft/MyLocalModItem.xaml.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/My Project/Resources.Designer.vb
  Plain Craft Launcher 2/My Project/Resources.resx
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
  Plain Craft Launcher 2/Resources/Imazen.WebP.dll
  Plain Craft Launcher 2/Resources/libwebp32.dll
  Plain Craft Launcher 2/Resources/libwebp64.dll
Labels: 处理中, · 新功能, 🟥 高

#3940 微软登录设备代码流
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
Labels: 处理中, · 新功能, 🟥 高, 🚫 阻碍者

#4779 Fix #3868
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
Labels: · Bug, 等待确认
