Repository Meloong-Git/PCL, pull requests merged in 2024-07, with the labels that each got.

#3885 添加 Follower's Cape 的翻译
  Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
Labels: 处理中, · 优化, 🟨 中

#4093 简化了 Java 搜索时的一大堆 SearchEntry.Contains
  Plain Craft Launcher 2/Modules/Minecraft/ModJava.vb
Labels: 处理中, · 优化, 🟩 低

#4058 为版本设置添加启动前内存优化
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml.vb
Labels: 处理中, · 优化, 🟨 中

#4138 修复追随者披风不能被汉化的 bug
  Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
Labels: · Bug, 等待确认

#4143 Fix #3819 #4151
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginAuth.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml
Labels: 处理中, · Bug, 🟩 低

#4155 只有一首音乐时右键重播
  Plain Craft Launcher 2/Modules/ModMusic.vb
Labels: 处理中, · 优化, 🟩 低

#4060 完成 #3997 允许启动当前版本
  Plain Craft Launcher 2/Modules/ModEvent.vb
  Plain Craft Launcher 2/Resources/Custom.xaml
Labels: 处理中, · 优化, 🟩 低

#4045 NeoForge 支持
  Plain Craft Launcher 2/Controls/MyCard.vb
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Images/Blocks/NeoForge.png
  Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadNeoForge.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadNeoForge.xaml.vb
  Plain Craft Launcher 2/Pages/PageSelectRight.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionModDisabled.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionOverall.xaml
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
  Plain Craft Launcher 2/Resources/Custom.xaml
Labels: 处理中, · 新功能, 🟥 高

#4167 Comma fix in `MySkin.xaml.vb` code
  Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
Labels: · Bug, 等待确认

#4193 Fix #4179
  Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
Labels: 处理中, · Bug, 🟪 极高

#4204 Fix #4183
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
Labels: 处理中, · Bug, 🟪 极高

#4219 修复使用绝对路径导致的编译问题
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: 处理中, · 优化, 🟩 低

#4349 Readme 徽标更改爱发电 net->com
  README.md
Labels: · 优化, 等待确认

#3945 所有4月1日发布的版本自动视为愚人节版
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadClient.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
Labels: 处理中, · 优化, 🟩 低
