Repository Meloong-Git/PCL, pull requests merged in 2025-02, with the labels that each got.

#5611 Feat:优化 Actions 文件
  .github/workflows/build.yml
Labels: · 优化, 等待确认

#5508 Chore:移除 ClientToken & 对 ModLaunch 刷新请求部分进行解耦合
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
Labels: 处理中, · 优化, 🟨 中

#5523 修改 Referer 的字段顺序以符合正常语义
  Plain Craft Launcher 2/Modules/ModSecret.vb
Labels: 处理中, · 优化, 🟨 中

#5526 读取MMC整合包instance.cfg中的JvmArgs参数
  Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
Labels: 处理中, · 优化, 🟨 中

#5634 Revise GrassPath translation
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionOverall.xaml
  Plain Craft Launcher 2/Resources/Custom.xaml
Labels: 处理中, · Bug, 🟩 低

#5650 修复：没读取 loaders 字段
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
Labels: · Bug, 等待确认
