Repository Meloong-Git/PCL, pull requests merged in 2025-04, with the labels that each got.

#5899 Fix：重选Fabric后FabricAPI不再自动选择
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
Labels: 处理中, · Bug, 🟥 高

#6025 fix(ModDownloadLib): #5920 造成的无法下载 OptiFine
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
Labels: · Bug, 等待确认

#6042 fix(FormMain): 2.9.3 没有更新日志
  Plain Craft Launcher 2/FormMain.xaml.vb
Labels: 处理中, · Bug, 🟥 高

#5967 chore(MySkin): 增加渴望披风的翻译
  Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
Labels: 处理中, · 优化, 🟥 高

#6053 chore: 筛选器增加版本 1.21.5
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadMod.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadPack.xaml
Labels: 处理中, · 优化, 🟥 高

#6138 fix(Setup): 下载速度限制的配置项不会在打开程序时被读取
  Plain Craft Launcher 2/Application.xaml.vb
Labels: 处理中, · Bug, 🟥 高

#6116 fix:识别问题
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadClient.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
Labels: 处理中, · Bug, 🟥 高

#6150 chore:忽略 system32 的 Java
  Plain Craft Launcher 2/Modules/Minecraft/ModJava.vb
Labels: 处理中, · 优化, 🟥 高

#5792 Fix：鼠标保持移动时抬起仍可继续改变窗口大小
  Plain Craft Launcher 2/Controls/MyResizer.vb
Labels: 处理中, · Bug, 🟨 中

#6101 fix(ModModPack): 解压压缩包进度可能超过 100%
  Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
Labels: 处理中, · Bug, 🟨 中

#5896 fix(PageSetupUI):修改显示文本
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml
Labels: 处理中, · Bug, 🟨 中

#5781 fix(ModJava):错误将下载目录的 Java 当作特定路径 Java
  Plain Craft Launcher 2/Modules/Minecraft/ModJava.vb
Labels: 处理中, · Bug, 🟨 中

#5773 fix(BtnDisplayRename_Click)：在重命名前检查路径
  Plain Craft Launcher 2/Controls/MyMsg/MyMsgInput.xaml.vb
Labels: · Bug, 等待确认

#4359 支持下载光影包
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Modules/Minecraft/MyCompItem.xaml.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadShader.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadShader.xaml.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: · 新功能, ✨ 尝鲜特性

#4360 支持下载数据包
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
  Plain Craft Launcher 2/Modules/Minecraft/MyCompItem.xaml.vb
  Plain Craft Launcher 2/Modules/ModMain.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadDataPack.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadDataPack.xaml.vb
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: · 新功能, ✨ 尝鲜特性

#6019 fix(ModLaunch): 启动脚本乱码
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
Labels: 处理中, · Bug, 🟨 中

#6137 fix(ModLoader): 不应当显示的加载器的进度也被计入到显示的总进度中
  Plain Craft Launcher 2/Modules/Base/ModLoader.vb
Labels: 处理中, · Bug, 🟨 中

#6197 feat(MyMsgLogin):增加账号被封禁时的错误提示
  Plain Craft Launcher 2/Pages/PageLaunch/MyMsgLogin.xaml.vb
Labels: 处理中, · 优化, 🟨 中

#5775 Fix: 在点击刷新按钮后对应的MyListItem显示不正确
  Plain Craft Launcher 2/Controls/MyListItem.xaml.vb
Labels: 处理中, · Bug, 🟩 低

#5776 Fix：通过网络获取到更多可更新模组时未同步至‘可更新’模组列表视图
  Plain Craft Launcher 2/Modules/Minecraft/ModMod.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionMod.xaml.vb
Labels: 处理中, · Bug, 🟩 低

#5976 fix(PageDownloadInstall): 打断安装预览页面进入动画后再次切换至下载页面时显示错误
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
Labels: 处理中, · Bug, 🟨 中
