Repository Meloong-Git/PCL, pull requests merged in 2025-07, with the labels that each got.

#6407 Refactor(Network):用 HttpClient 代替已经过时的 WebRequest、WebClient、ServicePointManager
  .github/workflows/build.yml
  Plain Craft Launcher 2/App.config
  Plain Craft Launcher 2/Modules/Base/ModNet.vb
  Plain Craft Launcher 2/Modules/ModSecret.vb
Labels: 处理中, · 优化, 🟪 极高

#6473 fix(PageDownloadCompDetail): 部分原版可用的光影无法显示可下载的游戏版本
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageDownloadCompDetail.xaml.vb
Labels: 处理中, · Bug, 🟦 小更改

#6527 feat: 支持识别因为微软账号被标记为可疑活动导致登陆失败
  Plain Craft Launcher 2/Pages/PageLaunch/MyMsgLogin.xaml.vb
Labels: 处理中, · 优化, 🟦 小更改

#6585 chore: 修改资源筛选版本
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageComp.xaml
Labels: 处理中, · 优化, 🟦 小更改

#6587 fix(java): JVM 崩溃导致错误将版本号识别为 JDK/JRE 64
  Plain Craft Launcher 2/Modules/Minecraft/ModJava.vb
Labels: 处理中, · Bug, 🟦 小更改

#6626 chore: 更新仓库指向仓库的链接
  .github/ISSUE_TEMPLATE/bug1.yml
  .github/ISSUE_TEMPLATE/bug2.yml
  .github/ISSUE_TEMPLATE/bug9.yml
  .github/ISSUE_TEMPLATE/ch.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature.yml
  LICENCE
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModJava.vb
  Plain Craft Launcher 2/Modules/ModMusic.vb
  Plain Craft Launcher 2/Pages/PageOther/PageOtherAbout.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherLeft.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Resources/Custom.xaml
  README.md
Labels: 处理中, · 优化, 🟦 小更改

#6795 chore: 自动搜索java路径添加 ~/.jdks
  Plain Craft Launcher 2/Modules/Minecraft/ModJava.vb
Labels: 处理中, · 优化, 🟦 小更改

#6717 feat:去掉“刷新头像”和“修改披风”之间的线
  Plain Craft Launcher 2/Pages/PageLaunch/PageLoginMsSkin.xaml
Labels: 处理中, · 优化, 🟦 小更改

#6594 fix(ModSecret): 开源版本龙猫蓝配色错误
  Plain Craft Launcher 2/Modules/ModSecret.vb
Labels: 处理中, · Bug, 🟥 高

#6685 imp(download): 改进可选组件互斥逻辑
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
Labels: 处理中, · 优化, 🟥 高

#6772 fix(Drop): 文件拖拽修复
  Plain Craft Launcher 2/FormMain.xaml.vb
  Plain Craft Launcher 2/Modules/Base/ModDragHelper.vb
  Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Labels: 处理中, · Bug, 🟥 高

#6706 fix: 搜索旧版本 Forge mod 崩溃
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
Labels: 处理中, · Bug, 🟥 高

#6445 fix(PageVersionOverall): 重命名版本时会修改后缀名且会修改不应重命名的文件或文件夹
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionOverall.xaml.vb
Labels: 处理中, · Bug, 🟥 高
