Repository Meloong-Git/PCL, pull requests merged in 2025-09, with the labels that each got.

#7151 Java搜索 支持jet 的基础sdk 以及 ~/.jdks 没匹配到可用项修复
  Plain Craft Launcher 2/Modules/Minecraft/ModJava.vb
Labels: 处理中, · 优化, 🟦 小更改

#7071 fix(ModCrash): 错误分析误报 night config 存在问题，但实际上是配置文件损坏
  Plain Craft Launcher 2/Modules/Minecraft/ModCrash.vb
Labels: 处理中, · Bug, 🟦 小更改

#7057 fix(ModLaunch): 未将部分错误识别为超时
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
Labels: 处理中, · Bug, 🟦 小更改

#7028 feat(PageVersionExport): 打包整合包时支持添加 TaCZ 枪包
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionExport.xaml
Labels: 处理中, · 优化, 🟦 小更改

#6664 fix: 动画绑定失败
  Plain Craft Launcher 2/Controls/MyPageLeft.vb
  Plain Craft Launcher 2/Controls/MyPageRight.vb
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageDownloadCompDetail.xaml
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageDownloadDataPack.xaml
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageDownloadMod.xaml
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageDownloadPack.xaml
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageDownloadResourcePack.xaml
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageDownloadShader.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadClient.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadFabric.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadForge.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLiteLoader.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadNeoForge.xaml
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadOptiFine.xaml
  Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchRight.xaml
  Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchRight.xaml.vb
  Plain Craft Launcher 2/Pages/PageLink/PageLinkFeedback.xaml
  Plain Craft Launcher 2/Pages/PageLink/PageLinkIoi.xaml
  Plain Craft Launcher 2/Pages/PageLink/PageLinkLeft.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherAbout.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherHelp.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherHelpDetail.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherLeft.xaml
  Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml
  Plain Craft Launcher 2/Pages/PageSelectLeft.xaml
  Plain Craft Launcher 2/Pages/PageSelectRight.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLeft.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLink.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml
  Plain Craft Launcher 2/Pages/PageSpeedRight.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionExport.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionLeft.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionMod.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionOverall.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml
Labels: 处理中, · Bug, 🟨 中
