Repository Meloong-Git/PCL, pull requests merged in 2025-03, with the labels that each got.

#5777 refactor(McInstallLoader):始终将 OptiFine 作为 Mod 安装
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
Labels: 处理中, · Bug, 🟪 极高

#5818 修复编码
  Plain Craft Launcher 2/Modules/Base/ModBase.vb
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
Labels: 处理中, · Bug, 🟥 高

#5785 feat(ModLaunch):允许不使用 JLW
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml.vb
Labels: 处理中, · 优化, 🟥 高

#5415 优化：自动切换到默认音频设备
  Plain Craft Launcher 2/Modules/ModMusic.vb
Labels: 处理中, · 优化, 🟥 高

#5861 fix(PageSetupLaunch):提示错误
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml
Labels: · Bug, 等待确认

#5863 Fix(PageVersionExport):没有刷新配置
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionExport.xaml.vb
Labels: 处理中, · Bug, 🟥 高

#5795 Fix：在特定情况下，即使可用内存大于预计分配的内存，仍出现“（可用 xx GB）“字样
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml.vb
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml.vb
Labels: 处理中, · Bug, 🟨 中

#5845 新功能：自动修改显卡设置
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
  Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml.vb
Labels: 完成, · 优化, 🟥 高

#5847 feat: Mod命名默认值增加“【】xxx”
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml
Labels: 处理中, · 优化, 🟨 中

#5996 chore: 防止小白无脑复制上面的 LittleSkin 地址到自动进入服务器
  Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml
Labels: · 优化, 等待确认

#5920 fix(ModDownloadLib): 1.14 及以上版本无法下载 OptiFine
  Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
Labels: 处理中, · Bug, 🟪 极高

#5938 fix(ModLaunch): 缓存问题导致切换语言失败
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
Labels: 处理中, · Bug, 🟥 高
