Repository Meloong-Git/PCL, pull requests merged in 2025-06, with the labels that each got.

#6437 fix:可能在获取正版皮肤时失败
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
Labels: 处理中, · Bug, 🟪 极高

#6570 chore(CurseForge): 增加新的 Fallback
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
Labels: 处理中, · 优化, 🟪 极高

#6472 fix(ModWatcher): Quilt 加载器错误窗口关闭后提示启动成功
  Plain Craft Launcher 2/Modules/Minecraft/ModWatcher.vb
Labels: 处理中, · Bug, 🟦 小更改
