Repository Meloong-Git/PCL, pull requests merged in 2025-01, with the labels that each got.

#5412 [可视化mod列表出错...]搜索Sand Filter时必报错
  Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
Labels: 处理中, · Bug, 🟥 高

#5260 添加办公室披风翻译
  Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
Labels: 处理中, · 优化, 🟨 中

#5337 通过修改 DPI 配置增强多屏幕 DPI 体验
  Plain Craft Launcher 2/App.config
  Plain Craft Launcher 2/app.manifest
Labels: 处理中, · 优化, 🟨 中

#5398 搜索部分mod时未在mod下载详情页出现MC版本筛选
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
Labels: 处理中, · Bug, 🟨 中

#5414 加载图标过于靠下
  Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml
Labels: 处理中, · 优化, 🟨 中

#5400 “设置/个性化/功能隐藏”字样在PCL2小窗口时不能完整显示文本
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml
Labels: 处理中, · 优化, 🟩 低

#5404 当在版本设置中连续按下mod右侧的“删除”按钮时，g概率导致PCL2崩溃。
  Plain Craft Launcher 2/Modules/Minecraft/MyLocalModItem.xaml.vb
Labels: 处理中, · Bug, 🟩 低
