Repository Meloong-Git/PCL, pull requests merged in 2025-05, with the labels that each got.

#6340 fix(FileDrag): 鼠标位于可编辑文字控件上无法完成向窗口的文件拖放
  Plain Craft Launcher 2/FormMain.xaml.vb
Labels: 处理中, · Bug, 🟥 高

#6234 chore:修改命名
  Plain Craft Launcher 2/Pages/PageDownload/Comp/PageDownloadResourcePack.xaml
Labels: 处理中, · 优化, 🟥 高

#6227 fix: 极小概率在主页卡片卡出“内容见 ModSetup” 的 Hint
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml.vb
Labels: 处理中, · Bug, 🟥 高

#6318 fix(PageSetupUI): 修正功能隐藏中的选项卡名称
  Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml
Labels: 处理中, · Bug, 🟥 高

#6257 fix:使用 HTTP 协议获取皮肤导致被劫持
  Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
Labels: 处理中, · Bug, 🟨 中

#6347 fix(LaunchArg): 默认窗口大小错误
  Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
Labels: 处理中, · Bug, 🟨 中

#4401 读取MCBBS整合包文件中的Jvm和Launch参数
  Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
Labels: 处理中, · 新功能, 🟩 低

#5771 fix(PageVersionMod): 在模组列表中划动鼠标选择时如果鼠标在列表之外松开会导致无法与悬浮卡片交互
  Plain Craft Launcher 2/Pages/PageVersion/MyLocalModItem.xaml.vb
Labels: 处理中, · Bug, 🟨 中
